### PR TITLE
Make program_info state not be global

### PR DESCRIPTION
**Pull request by dthaler**
This is part 1 of 3 for issue #113

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Comment by dthaler** [comment]
Rebased to resolve merge conflict

**Comment by elazarg** [comment]
The PR itself looks good. I don't feel very comfortable with the idea though. Program info is (ideally) a constant, initialize once for each run of the verifier - it has nothing to do with any specific instance of an abstract domain, for example. So for each "task" it makes sense for it to be global (being constant); we could (in principle, not that I would recommend that) recompile it for each program we analyze. The only concrete concern I see is if we move to multithreading at some point, but in such case it can be thread-local I guess?

I know this approach is not standard, and I am going to merge this PR. Nevertheless I would like to hear your take on this.

**Comment by dthaler** [comment]
We do need multithreading for our use cases.
I think you're right it could be thread_local.  Would you prefer that approach instead then?

**Comment by elazarg** [comment]
I think it would be better, but I'll leave the choice to you.

One unrelated question: What happens in this PR if we have something like
```
    // two branches join; inv=TOP, then
    r0 = 1
    foo(r0, r1)  // foo requires program_info
```
IIUC, `r0 = 1` transfers TOP (where `m_program_info` is NULL) to non-TOP, where it shouldn't be. How does that happen?

**Comment by dthaler** [comment]
Let me see if I can get the thread_local approach working.

**Comment by dthaler** [comment]
Replaced by #198

**Pull request closed without merging**
