### PR TITLE
Reintroduce descending_iterations constant

### PR DESCRIPTION
**Pull request by elazarg**
I have removed this constant in the past ([it does exist in crab](https://github.com/seahorn/crab/blob/3d01b5564367db5211e11dda51775a0c4d66fee4/include/crab/iterators/interleaved_fixpoint_iterator.hpp#L109)), but without this constant, the verifier itself does not halt in #139.

For some reason, analysis of simple loops that increment a register do halt even without this constant.

Signed-off-by: Elazar Gershuni <elazarg@gmail.com>

### CODE REVIEW

**Comment by caballa** [comment]
This constant is for performing narrowing a finite number of times. Narrowing is used together with widening and can produce more precise results. Narrowing should be always used when widening is used. I didn't look yet how you try to prove termination but more precise invariants should help to prove more often termination

**Comment by elazarg** [comment]
My question is not about proof of termination, it is about termination of the verifier, without this constant. Analysis of a simple loop that increments a register, terminates. But when I increment the program counter, it does not.

**Comment by caballa** [comment]
Sorry I didn't understand the question. The descending phase terminates on the condition that the narrowing operation satisfies the condition that if it's applied a finite number of times the analysis converges. There are two ways of implementing this: (1) define a proper narrowing operator for each abstract domain, or alternatively (2) run the analyzer without widening a **finite** number of times and replacing `narrowing` with `meet`.  The advantage of (2) is that it's abstract domain independent and AFIK the results are not worse than defining specific narrowing operator per domain.  That's why that constant is super important, because it ensures that (2) is run a finite number of times. In my experience, the analysis doesn't improve after 1 or 2 descending iterations.

**Comment by elazarg** [comment]
And why the termination analysis does not halt without it, but safety analysis does? It's supposed to work in exactly the same way (in the first phase).

Also, do you approve this PR? Or have I missed something.

**Comment by caballa** [comment]
Yes, I approve the PR.
Can you print the invariants for the case where it doesn't terminate? 
Let me speculate. I assume that the termination analysis adds an extra counter variable that it's incremented until it reaches some threshold. So after the ascending phase the counter has the interval `[0, N]` where `N` is the threshold. Then, if we apply the descending phase without enforcing termination then it is possible that after each descending iteration the counter takes the values `[0,N], [0,N-1], [0,N-2], ....`.  This sequence can be too long.

**Comment by elazarg** [comment]
It jumps back and forth between `[4, oo]` and `[6,oo]`. Something like that.

**Comment by elazarg** [comment]
I guess discussion will be more on-topic in #139.

**Comment by caballa** [comment]
I would expect you get into an infinite (or too long) descending chain but you seem to get into a cycle. 
The use of the constant ensures termination in this case but it might hide some serious problem. 
I would like to run the example. 
Is it possible for you to write a C program that includes the termination instrumentation that I can look at it? and maybe run directly Crab on it?

**Comment by elazarg** [comment]
I don't think I can do that. The instrumentation fails only when it is implicit - that's what puzzled me.

**Comment by elazarg** [comment]
I believe this was spurious, and occurred only in the test that connected the exit to the entry, which is not possible now.

**Pull request merged**
