### PR TITLE
Replace NASA licensed patricia tree with BSD-2 licensed implementation

### PR DESCRIPTION
**Pull request by dthaler**
This change addresses the next file of those listed in issue #149.
I have not compared the performance against the perf before this change, only the correctness.

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Comment by elazarg** [comment]
I've found no difference in performance.

**Comment by dthaler** [comment]
> I've found no difference in performance.

Thanks for confirming!

**Comment by caballa** [comment]
It looks good. 

Just a note related to this. The offset map maintained by the array domain is global. This makes analysis faster and simpler at the expense of some extra memory consumption. To have "local" (one per basic block) offset maps will be required if we want to do inter-procedural analysis. Having local offset maps is not hard but it requires extra operations from the radix tree implementation as "join", "meet", "rename", etc. In the patricia trees implementations, both join and meets are specializations of a "merge" function that takes two patricia trees and merge them. My point is that we will need to extend radix trees for supporting this merge operation if it is already available.

FYI, this is the offset_map` class used in Crab (https://github.com/seahorn/crab/blob/master/include/crab/domains/array_adaptive.hpp#L477)  extended with join and meet.

**Comment by dthaler** [comment]
@elazarg since Jorge said "it looks good", is there anything else blocking merging of this PR?

**Comment by elazarg** [comment]
Hmm I guess not.

**Pull request merged**
