### PR TITLE
Add support for using Boost as the bignum library

### PR DESCRIPTION
**Pull request by dthaler**
This PR adds support for using Boost rather than GMP as the multiprecision integer library.
This leaves GMP as the default for now, but Boost can be chosen via the `-DUSE_GMP=OFF` cmake option, as in:
```
cmake -DUSE_GMP=OFF -B build -DCMAKE_BUILD_TYPE=Release
```

bignums.hpp is just renamed to bignums_gmp.hpp without any changes.  Github seems to show them as completely removed/new but it's just renamed.

Fixes issue #111

Signed-off-by: Dave Thaler <dthaler@microsoft.com>

### CODE REVIEW

**Comment by elazarg** [comment]
I assume git doesn't catch the rename because the file still exists?

Comparing the options on my machine (a single run), there seems to be very small difference in performance, and usually boost's version is the faster one.

**Comment by elazarg** [comment]
I think we want to add a CI job that compiles with boost.

**Comment by dthaler** [comment]
> I assume git doesn't catch the rename because the file still exists?
> 
> Comparing the options on my machine (a single run), there seems to be very small difference in performance, and usually boost's version is the faster one.

I observe the same on my machine (3 to 4% faster on average).  In addition, the memory used is also usually slightly less (3 to 4% less kb on average).

Since overall the cpu time and memory are better, I've now switched the default to boost's version if that's ok.

> I think we want to add a CI job that compiles with boost.

Done, there's now 3 jobs rather than just 2 CI jobs

**Comment by caballa** [comment]
This is really nice. I should port it to Crab.

**Pull request merged**
