### PR TITLE
Add copyright/license headers to files

### LINKED ISSUE #105: Add appropriate header to top of each code file
To keep code provenance clean, I would recommend an approach followed by many other open source projects used in production, which list the Copyright and License at the top of each file.  It could be as short as two lines.

E.g., the Open Enclave SDK (for which I am a maintainer) uses this:

> // Copyright (c) Open Enclave SDK contributors.
> // Licensed under the MIT License.

The first line means that each contributor retains the copyright, and it intentionally does not have copyright any individual or organization since there may be pull requests from different people over time that touch the same file.

Kubernetes uses a similar 1-line copyright (The Kubernetes Authors.) but copies the Apache license into each file, as in this example:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/gc/gc_admission.go

Iotivity (for which I was a maintainer) is similar, with a 1-line copyright by the original contributor of the file and copies the Apache license into each file, as in this example:
https://github.com/iotivity/iotivity/blob/master/resource/src/OCResource.cpp
The copyright statement being only the original contributor of each file is something many people don't like and why other projects usually don't follow that approach.

AllJoyn (for which I was a maintainer) similarly used a 1-line copyright by contributors and copied the Apache license into each file, as in this example:
https://github.com/alljoyn/core-alljoyn/blob/master/alljoyn_core/src/AllJoynCrypto.h

My opinion is that since the LICENSE file is in the root of the ebpf-verifier repo, and it's a standard OSI-approved license (and indeed it's the _same_ license that the Open Enclave SDK uses), that the MIT license need not be copied into each file and a simple two-line comment would suffice.

I'd suggest something like this:
// Copyright (c) Prevail Verifier contributors.
// Licensed under the MIT License.

This would make it clear which files are MIT licensed vs which are not, and what the copyright is on each file.

The Open Enclave SDK also uses a git checker to require that every new file has such a notice at the top.  I'd be happy to contribute that here if others agree with such an approach.

### PR DESCRIPTION
**Pull request by dthaler**
This pull request does two things:
1) It adds headers to existing files.  (I am not certain they are all correct in this PR, so please review.)
2) It checks any new commits to make sure files have such headers.

The .check-license.ignore file lists file types, directories, and files, that intentionally do not have the usual license header for this project.

Fixes #105

### CODE REVIEW

**Comment by elazarg** [comment]
LGTM. I guess we need @caballa here too.

**Comment by elazarg** [comment]
LGTM. I guess we need @caballa here too.

**Comment by dthaler** [comment]
> LGTM. I guess we need @caballa here too.

Since this PR does not address issue #104 assigned to @caballa (e.g., it does not have any notice of modifications), maybe this one can be merged and then Jorge can do any corrections in a PR that addresses 104? Or if you prefer to wait for Jorge to review this PR that's ok too.

**Comment by elazarg** [comment]
OK.

**Pull request merged**
